# Generated by Django 5.0.1 on 2026-01-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='previous_status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
